{{- define "eric-adp-nodejs-chassis-service.product-labels" }}
app.kubernetes.io/name: {{ template "eric-adp-nodejs-chassis-service.name" . }}
app.kubernetes.io/version: {{ template "eric-adp-nodejs-chassis-service.version" . }}
app.kubernetes.io/instance: {{ .Release.Name | quote }}
app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
helm.sh/chart: {{ include "eric-adp-nodejs-chassis-service.chart" . }}
{{- end}}
