{{- $authorizationProxy := fromJson (include "eric-adp-nodejs-chassis-service.authz-proxy-values" .) -}}
{{- if $authorizationProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-adp-nodejs-chassis-service.authz-proxy-service-name" . }}-authorizationrules
  labels:
    {{- $authProxyLabels := include "eric-adp-nodejs-chassis-service.authz-proxy-labels" . | fromYaml -}}
    {{- $commonLabels := include "eric-adp-nodejs-chassis-service.labels" . | fromYaml -}}
    {{- include "eric-adp-nodejs-chassis-service.mergeLabels" (dict "location" .Template.Name "sources" (list $authProxyLabels $commonLabels)) | trim | nindent 4 }}
  annotations:
{{- include "eric-adp-nodejs-chassis-service.annotations" . | nindent 4 }}
data:
  authz-proxy-authorizationrules.yaml: |
{{ .Values.authorizationProxy.authorizationRules | indent 4 }}
{{- end -}}
