apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-adp-nodejs-chassis-service.name" . }}-faultmappings-configmap
  labels:
{{- include "eric-adp-nodejs-chassis-service.labels" . | nindent 4 }}
  annotations:
{{- include "eric-adp-nodejs-chassis-service.annotations" . | nindent 4 }}
data:
  eric-adp-nodejs-chassis-service.json: |-
{{ .Files.Get "static/faultmappings/eric-adp-nodejs-chassis-service-faultmapping.json" | indent 4 }}