{{- if and (.Values.ingress.enabled) (not .Values.ingress.tls.existingSecret) (.Values.ingress.tls.enabled) -}}
apiVersion: certm.sec.ericsson.com/v1
kind: ExternalCertificate
metadata:
  name: {{ include "eric-adp-nodejs-chassis-service.name" . }}-ingress-external-server-cert
  labels:
    {{- include "eric-adp-nodejs-chassis-service.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-adp-nodejs-chassis-service.annotations" . | nindent 4 }}
spec:
  generated-secret-name: {{ include "eric-adp-nodejs-chassis-service.name" . }}-ingress-external-server-cert
  generated-secret-type: tls
  asymmetric-key-certificate-name: {{ include "eric-adp-nodejs-chassis-service.ingress.asymmetricKeyCertName" . }}
{{- end -}}