{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "eric-adp-nodejs-chassis-service.name" . }}-pdb
  labels:
    {{- include "eric-adp-nodejs-chassis-service.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-adp-nodejs-chassis-service.annotations" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-adp-nodejs-chassis-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
