{{- $global := fromJson (include "eric-adp-nodejs-chassis-service.global" .) -}}
{{- if $global.security.tls.enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-adp-nodejs-chassis-service.name" . }}-http-server-cert
  labels:
    {{- include "eric-adp-nodejs-chassis-service.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-adp-nodejs-chassis-service.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-adp-nodejs-chassis-service.name" . }}-http-server-cert
    certificateName: srvcert.pem
    privateKeyName: srvprivkey.pem
  certificate:
    subject:
      cn: {{ include "eric-adp-nodejs-chassis-service.name" . }}
    subjectAlternativeName:
      dns:
        {{- if .Values.metrics.enabled }}
        - certified-scrape-target
        {{- end }}
        - {{ include "eric-adp-nodejs-chassis-service.name" . }}-http
        - {{ include "eric-adp-nodejs-chassis-service.name" . }}-http.{{ .Release.Namespace }}
        - {{ include "eric-adp-nodejs-chassis-service.name" . }}-http.{{ .Release.Namespace }}.svc
        - {{ include "eric-adp-nodejs-chassis-service.name" . }}-http.{{ .Release.Namespace }}.svc.cluster
        - {{ include "eric-adp-nodejs-chassis-service.name" . }}-http.{{ .Release.Namespace }}.svc.cluster.local
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: true
{{- end }}
