{{- if (index .Values "eric-lm-combined-server").enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: eric-lm-combined-server-db-secret
type: Opaque
data:
  # postgres custom user and password
  custom-user: {{ "lmuser" | b64enc | quote }}
  custom-pwd: {{ "custom-pwd" | b64enc | quote }}

  # postgres super user and password
  super-user: {{ "postgres" | b64enc | quote }}
  super-pwd: {{ "postgres" | b64enc | quote }}

  # postgres metrics user and password
  metrics-user: {{ "exporter" | b64enc | quote }}
  metrics-pwd: {{ "exporter" | b64enc | quote }}

  # postgres replication user and password
  replica-user: {{ "replica" | b64enc | quote }}
  replica-pwd: {{ "replica" | b64enc | quote }}
{{ end }}
